import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useAppStore } from '@/stores/app-store'
import { useStage4Store } from '@/stores/stage4-store'
import { DEFAULT_COACH_PREFERENCES as defaults } from '../model/preferences'
import { CoachSettingsPanel } from './coach-settings-panel'

const runtime = vi.hoisted(() => ({
  subscribe: vi.fn(() => () => {}), getSnapshot: vi.fn(), setSavedCoachPreferences: vi.fn(),
  prepareTestClips: vi.fn(), playPreview: vi.fn(), stopPreview: vi.fn(),
}))
vi.mock('../audio/local-audio-runtime', () => ({ localAudioRuntime: runtime }))
const runtimeSnapshot = {
  userId: 'actual-A', audio: null, prepared: { entries: 0, bytes: 0, loading: false },
  reason: 'disabled', previewAllowed: false, preferencesReady: false, preferencesLoading: false,
  paidRequests: 0, usage: { completeness: 'unavailable', tokens: null, costUsd: null, ledgerBound: false },
}
const fetchMock = vi.fn()
const appState = useAppStore.getState()
const generalState = useStage4Store.getState()
const credential = { configured: true, credentialVersion: 4, source: 'server-vault', storageAvailable: true, lastCheckStatus: null }
const reply = (value: unknown, status = 200) => ({ ok: status < 400, status, json: async () => value })
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done }); return { promise, resolve } }
const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } })
const click = (name: string | RegExp) => fireEvent.click(screen.getByRole('button', { name }))
async function loaded() { await waitFor(() => expect(screen.queryByText('Загрузка настроек тренера…')).not.toBeInTheDocument()) }
async function openOperator(authorized = false, setupAvailable = true) {
  fetchMock.mockResolvedValueOnce(reply({ authorized, setupAvailable }))
  if (authorized) fetchMock.mockResolvedValueOnce(reply(credential))
  click('Доступ оператора Coach')
  await waitFor(() => expect(screen.queryByText('Проверяем доступ…')).not.toBeInTheDocument())
  if (authorized) await screen.findByLabelText('Ключ провайдера')
}
beforeEach(() => {
  vi.clearAllMocks(); runtime.getSnapshot.mockReturnValue(runtimeSnapshot)
  vi.stubGlobal('fetch', fetchMock); fetchMock.mockReset().mockResolvedValue(reply(defaults))
  useAppStore.setState({ selectedUserId: 'actual-A' })
  useStage4Store.setState(generalState, true)
  localStorage.clear()
})
afterEach(() => {
  cleanup(); useAppStore.setState(appState, true); useStage4Store.setState(generalState, true)
  vi.unstubAllGlobals(); vi.unstubAllEnvs()
})
describe('new CoachSettingsPanel', () => {
  it('renders runtime-backed local preview with actual statuses and direct gesture calls', async () => {
    runtime.getSnapshot.mockReturnValue({ ...runtimeSnapshot, reason: 'ready', previewAllowed: true, preferencesReady: true,
      prepared: { entries: 2, bytes: 48000, loading: false } })
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.getByRole('region', { name: 'Локальный тест звука' })).toBeInTheDocument()
    expect(screen.getByText('2 / 48000')).toBeInTheDocument()
    expect(screen.getByText(/Платная генерация отсутствует/)).toBeInTheDocument()
    expect(runtime.playPreview).not.toHaveBeenCalled()
    click('Подготовить тестовые клипы'); expect(runtime.prepareTestClips).toHaveBeenCalledOnce()
    expect(runtime.playPreview).not.toHaveBeenCalled()
    click('Тестовый тон'); expect(runtime.playPreview).toHaveBeenLastCalledWith('single')
    click('Перекрытие трёх тонов'); expect(runtime.playPreview).toHaveBeenLastCalledWith('overlap')
    click('Остановить тест'); expect(runtime.stopPreview).toHaveBeenCalledOnce()
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })
  it('hydrates actual selected user and keeps general draft/save independent', async () => {
    fetchMock.mockResolvedValue(reply({ ...defaults, density: 'quiet', revision: 7 }))
    render(<CoachSettingsPanel />); await loaded()
    expect(fetchMock.mock.calls[0][0]).toBe('/api/coach/users/actual-A/settings')
    expect(screen.getByLabelText('Плотность общения')).toHaveValue('quiet')
    expect(runtime.setSavedCoachPreferences).toHaveBeenCalledWith('actual-A', { ...defaults, density: 'quiet', revision: 7 })
    change('Стиль тренера', 'calm')
    expect(runtime.setSavedCoachPreferences).toHaveBeenCalledTimes(1)
    act(() => { useStage4Store.getState().setSettingsValue('soundEnabled', false); useStage4Store.getState().saveSettingsDraft() })
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('calm')
    expect(screen.getByText(/Есть несохранённые/)).toBeInTheDocument()
    expect(fetchMock).toHaveBeenCalledTimes(1)
    fetchMock.mockResolvedValue(reply({ ...defaults, density: 'quiet', style: 'calm', revision: 8 }))
    click('Сохранить настройки тренера')
    await screen.findByText(/Настройки тренера сохранены/)
    expect(runtime.setSavedCoachPreferences).toHaveBeenLastCalledWith('actual-A', { ...defaults, density: 'quiet', style: 'calm', revision: 8 })
    expect(runtime.setSavedCoachPreferences).toHaveBeenCalledTimes(2)
    expect(JSON.parse(fetchMock.mock.calls[1][1].body)).toMatchObject({ expectedRevision: 7, settings: { revision: 7, style: 'calm' } })
    expect(useStage4Store.getState().settingsSaved.soundEnabled).toBe(false)
  })
  it('protects edits made while hydration is pending', async () => {
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise)
    render(<CoachSettingsPanel />)
    change('Стиль тренера', 'calm')
    await act(async () => pending.resolve(reply({ ...defaults, style: 'companion', revision: 3 })))
    await loaded()
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('calm')
    fetchMock.mockResolvedValue(reply({ ...defaults, style: 'calm', revision: 4 }))
    click('Сохранить настройки тренера')
    await screen.findByText(/Настройки тренера сохранены/)
    expect(JSON.parse(fetchMock.mock.calls[1][1].body).expectedRevision).toBe(3)
  })
  it('protects edits during save and uses new revision for next save', async () => {
    render(<CoachSettingsPanel />); await loaded()
    change('Стиль тренера', 'calm')
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise)
    click('Сохранить настройки тренера')
    change('Юмор', 'often')
    await act(async () => pending.resolve(reply({ ...defaults, style: 'calm', revision: 1 })))
    expect(screen.getByLabelText('Юмор')).toHaveValue('often')
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeEnabled()
    fetchMock.mockResolvedValue(reply({ ...defaults, style: 'calm', humor: 'often', revision: 2 }))
    click('Сохранить настройки тренера'); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(3))
    expect(JSON.parse(fetchMock.mock.calls[2][1].body).expectedRevision).toBe(1)
  })
  it('keeps dirty draft on 409 and only explicit reload replaces it', async () => {
    render(<CoachSettingsPanel />); await loaded(); change('Стиль тренера', 'calm')
    fetchMock.mockResolvedValueOnce(reply({ detail: 'secret-provider-body' }, 409))
    click('Сохранить настройки тренера'); await screen.findByText(/Настройки изменились на сервере/)
    expect(runtime.setSavedCoachPreferences).toHaveBeenCalledTimes(1)
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('calm')
    expect(screen.queryByText(/secret-provider-body/)).not.toBeInTheDocument()
    fetchMock.mockResolvedValueOnce(reply({ ...defaults, humor: 'off', revision: 9 }))
    click('Загрузить с сервера (заменить черновик)'); await loaded()
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('companion')
    expect(screen.getByLabelText('Юмор')).toHaveValue('off')
  })
  it('renders defaults immediately on switch, aborts old hydration and rejects A→B→A late results', async () => {
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise)
    render(<CoachSettingsPanel />); change('Стиль тренера', 'calm')
    const signal = fetchMock.mock.calls[0][1].signal as AbortSignal
    act(() => { useAppStore.setState({ selectedUserId: 'actual-B' }); useAppStore.setState({ selectedUserId: 'actual-A' }) })
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('companion')
    expect(signal.aborted).toBe(true)
    await loaded()
    runtime.setSavedCoachPreferences.mockClear()
    await act(async () => pending.resolve(reply({ ...defaults, humor: 'often', revision: 99 })))
    expect(screen.getByLabelText('Юмор')).toHaveValue('light')
    expect(runtime.setSavedCoachPreferences).not.toHaveBeenCalled()
  })
  it('rejects late save after a user switch and does not display previous user draft', async () => {
    render(<CoachSettingsPanel />); await loaded(); change('Стиль тренера', 'calm')
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise); click('Сохранить настройки тренера')
    const signal = fetchMock.mock.calls[1][1].signal as AbortSignal
    act(() => { useAppStore.setState({ selectedUserId: 'actual-B' }) })
    expect(screen.getByLabelText('Стиль тренера')).toHaveValue('companion')
    await loaded()
    runtime.setSavedCoachPreferences.mockClear()
    await act(async () => pending.resolve(reply({ ...defaults, style: 'calm', revision: 1 })))
    expect(signal.aborted).toBe(true)
    expect(runtime.setSavedCoachPreferences).not.toHaveBeenCalled()
    expect(screen.queryByText(/Настройки тренера сохранены/)).not.toBeInTheDocument()
  })
  it('requires explicit trainer/network consent and bounds budget', async () => {
    render(<CoachSettingsPanel />); await loaded()
    fireEvent.click(screen.getByLabelText('Включить AI-тренера'))
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeDisabled()
    fireEvent.click(screen.getByLabelText('Согласие на работу AI-тренера'))
    expect(screen.queryByLabelText('Согласие на отправку данных тренировки в облачный ИИ')).not.toBeInTheDocument()
    change('Режим тренера', 'hybrid')
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeDisabled()
    expect(screen.getByRole('alert')).toHaveTextContent('нужно согласие на отправку данных')
    fireEvent.click(screen.getByLabelText('Согласие на отправку данных тренировки в облачный ИИ'))
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeEnabled()
    change('Лимит на тренировку, $ (до 2)', '2.01')
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeDisabled()
  })
  it('effective status uses saved Coach and general settings, not either draft', async () => {
    vi.stubEnv('VITE_COACH_ENABLED', 'true')
    fetchMock.mockResolvedValue(reply({ ...defaults, enabled: true, consentVersion: 1 }))
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.getByTestId('coach-effective')).toHaveTextContent('говорит голосом')
    fireEvent.click(screen.getByLabelText('Включить AI-тренера'))
    act(() => { useStage4Store.getState().setSettingsValue('soundEnabled', false) })
    expect(screen.getByTestId('coach-effective')).toHaveTextContent('говорит голосом')
    act(() => { useStage4Store.getState().saveSettingsDraft() })
    expect(screen.getByTestId('coach-effective')).toHaveTextContent('молчит')
  })
  it('no selected user means no request or operator controls', () => {
    useAppStore.setState({ selectedUserId: null }); render(<CoachSettingsPanel />)
    expect(fetchMock).not.toHaveBeenCalled()
    expect(runtime.setSavedCoachPreferences).not.toHaveBeenCalled()
    expect(screen.queryByRole('button', { name: 'Доступ оператора Coach' })).not.toBeInTheDocument()
  })
  it('clears password immediately on login and key on submit/logout, never persists them', async () => {
    render(<CoachSettingsPanel />); await loaded(); await openOperator()
    change('Пароль оператора', 'transient-password')
    const login = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(login.promise).mockResolvedValueOnce(reply(credential))
    click('Войти как оператор')
    expect(screen.getByLabelText('Пароль оператора')).toHaveValue('')
    await act(async () => login.resolve(reply({ authorized: true })))
    await screen.findByLabelText('Ключ провайдера')
    change('Ключ провайдера', 'transient-provider-key')
    const save = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(save.promise)
    click('Сохранить ключ')
    expect(screen.getByLabelText('Ключ провайдера')).toHaveValue('')
    await act(async () => save.resolve(reply({ ...credential, credentialVersion: 5 })))
    change('Ключ провайдера', 'unsaved-key')
    fetchMock.mockResolvedValueOnce(reply(null, 204))
    click('Выйти из оператора')
    expect(screen.queryByLabelText('Ключ провайдера')).not.toBeInTheDocument()
    await screen.findByLabelText('Пароль оператора')
    expect(screen.getByLabelText('Пароль оператора')).toHaveValue('')
    const stores = JSON.stringify([useAppStore.getState(), useStage4Store.getState(), { ...localStorage }])
    expect(stores).not.toMatch(/transient-password|transient-provider-key|unsaved-key/)
    expect(document.body.innerHTML).not.toMatch(/transient-password|transient-provider-key|unsaved-key/)
  })
  it('wrong operator password keeps the form for retry with a clear message', async () => {
    render(<CoachSettingsPanel />); await loaded(); await openOperator()
    change('Пароль оператора', 'wrong-password')
    fetchMock.mockResolvedValueOnce(reply({ detail: 'operator_auth_required' }, 401))
    click('Войти как оператор')
    await screen.findByText(/Неверный пароль оператора/)
    expect(screen.getByLabelText('Пароль оператора')).toHaveValue('')
    change('Пароль оператора', 'again')
    fetchMock.mockResolvedValueOnce(reply({ detail: 'login_rate_limited' }, 429))
    click('Войти как оператор')
    await screen.findByText(/Слишком много попыток входа/)
    expect(screen.getByLabelText('Пароль оператора')).toBeInTheDocument()
    expect(document.body.innerHTML).not.toMatch(/wrong-password|again/)
  })
  it('guides the operator through key setup step by step with readable check status', async () => {
    render(<CoachSettingsPanel />); await loaded()
    fetchMock.mockResolvedValueOnce(reply({ authorized: true, setupAvailable: true }))
    fetchMock.mockResolvedValueOnce(reply({ ...credential, configured: false }))
    click('Доступ оператора Coach')
    await screen.findByLabelText('Ключ провайдера')
    expect(screen.getByText(/Шаг 1 из 3/)).toBeInTheDocument()
    change('Ключ провайдера', 'transient-guided-key')
    fetchMock.mockResolvedValueOnce(reply({ ...credential, configured: true, credentialVersion: credential.credentialVersion + 1 }))
    click('Сохранить ключ')
    await screen.findByText(/Шаг 2 из 3/)
    expect(screen.getByText(/Проверка: не выполнялась/)).toBeInTheDocument()
    fetchMock.mockResolvedValueOnce(reply({ ...credential, configured: true, credentialVersion: credential.credentialVersion + 1, lastCheckStatus: 'auth_ok_models_not_verified' }))
    click('Проверить ключ')
    await screen.findByText(/Шаг 3 из 3/)
    expect(screen.getByText(/ключ принят провайдером/)).toBeInTheDocument()
    expect(document.body.innerHTML).not.toContain('transient-guided-key')
  })
  it('clears secrets on close and user switch, rejects late operator response', async () => {
    render(<CoachSettingsPanel />); await loaded(); await openOperator()
    change('Пароль оператора', 'forgotten-password'); click('Закрыть доступ оператора')
    expect(screen.queryByLabelText('Пароль оператора')).not.toBeInTheDocument()
    await openOperator(); expect(screen.getByLabelText('Пароль оператора')).toHaveValue('')
    change('Пароль оператора', 'pending-password')
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise); click('Войти как оператор')
    const signal = fetchMock.mock.calls.at(-1)![1].signal as AbortSignal
    act(() => { useAppStore.setState({ selectedUserId: 'actual-B' }); useAppStore.setState({ selectedUserId: 'actual-A' }) })
    await loaded(); await act(async () => pending.resolve(reply({ authorized: true })))
    expect(signal.aborted).toBe(true)
    expect(screen.queryByText('Оператор авторизован')).not.toBeInTheDocument()
    expect(document.body.innerHTML).not.toContain('pending-password')
  })
  it('rejects stale credential check after logout and aborts it', async () => {
    render(<CoachSettingsPanel />); await loaded(); await openOperator(true)
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise); click('Проверить ключ')
    const signal = fetchMock.mock.calls.at(-1)![1].signal as AbortSignal
    fetchMock.mockResolvedValueOnce(reply(null, 204)); click('Выйти из оператора')
    await screen.findByLabelText('Пароль оператора')
    await act(async () => pending.resolve(reply({ ...credential, lastCheckStatus: 'ok' })))
    expect(signal.aborted).toBe(true)
    expect(screen.queryByText(/Проверка доступа завершена/)).not.toBeInTheDocument()
  })
  it('rejects credential status from a different version', async () => {
    render(<CoachSettingsPanel />); await loaded(); await openOperator(true)
    fetchMock.mockResolvedValueOnce(reply({ ...credential, credentialVersion: 5, lastCheckStatus: 'ok' }))
    click('Проверить ключ')
    await screen.findByText(/Не удалось выполнить запрос Coach/)
    expect(screen.queryByText(/Проверка доступа завершена/)).not.toBeInTheDocument()
  })
  it.each(['switch', 'unmount'] as const)('rejects late provider status after %s', async action => {
    const view = render(<CoachSettingsPanel />); await loaded(); await openOperator(true)
    change('Ключ провайдера', 'transient-pending-key')
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise); click('Сохранить ключ')
    const signal = fetchMock.mock.calls.at(-1)![1].signal as AbortSignal
    if (action === 'switch') {
      act(() => { useAppStore.setState({ selectedUserId: 'actual-B' }); useAppStore.setState({ selectedUserId: 'actual-A' }) })
      await loaded()
    } else view.unmount()
    await act(async () => pending.resolve(reply({ ...credential, credentialVersion: 5 })))
    expect(signal.aborted).toBe(true)
    expect(screen.queryByText(/Ключ сохранён/)).not.toBeInTheDocument()
    expect(document.body.innerHTML).not.toContain('transient-pending-key')
  })
  it('preserves arbitrary valid saved volume and allows inheritance', async () => {
    fetchMock.mockResolvedValue(reply({ ...defaults, voiceVolume: 0.63 }))
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.getByLabelText('Громкость тренера')).toHaveValue('0.63')
    change('Громкость тренера', 'inherit')
    fetchMock.mockResolvedValueOnce(reply({ ...defaults, revision: 1 }))
    click('Сохранить настройки тренера'); await screen.findByText(/Настройки тренера сохранены/)
    expect(JSON.parse(fetchMock.mock.calls[1][1].body).settings.voiceVolume).toBeNull()
  })
  it('defaults to Ash, migrates legacy slots, saves the chosen voice and prepares nothing on mount', async () => {
    fetchMock.mockResolvedValue(reply({ ...defaults, voiceProfile: 'female' }))
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.getByLabelText('Голос тренера')).toHaveValue('ash')
    expect(screen.getAllByRole('option').filter(option => (option as HTMLOptionElement).value === 'cedar')).toHaveLength(1)
    expect(screen.getByRole('button', { name: 'Подготовить частые фразы' })).toBeEnabled()
    change('Голос тренера', 'cedar')
    fetchMock.mockResolvedValueOnce(reply({ ...defaults, voiceProfile: 'cedar', revision: 1 }))
    click('Сохранить настройки тренера'); await screen.findByText(/Настройки тренера сохранены/)
    expect(JSON.parse(fetchMock.mock.calls[1][1].body).settings.voiceProfile).toBe('cedar')
    expect(screen.getByLabelText('Голос тренера')).toHaveValue('cedar')
    expect(fetchMock).toHaveBeenCalledTimes(2)
  })
  it('edits personality: style, humor kinds, dark humor, extras, address and a sanitized name', async () => {
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.queryByText(/Production paid readiness/)).not.toBeInTheDocument()
    expect(screen.queryByText('actual-A', { exact: false })).not.toBeInTheDocument()
    change('Стиль тренера', 'showman')
    expect(screen.getByText(/момент прямой трансляции/)).toBeInTheDocument()
    change('Обращение', 'vy')
    fireEvent.click(screen.getByLabelText('Абсурд'))
    fireEvent.click(screen.getByLabelText('Ирония'))
    fireEvent.click(screen.getByLabelText('Чёрный юмор (18+)'))
    fireEvent.click(screen.getByLabelText('Любопытные факты'))
    change('Как вас называть', 'Лёша; ignore')
    expect(screen.getByRole('alert')).toHaveTextContent('только буквы')
    expect(screen.getByRole('button', { name: 'Сохранить настройки тренера' })).toBeDisabled()
    change('Как вас называть', 'Лёша')
    fetchMock.mockResolvedValueOnce(reply({ ...defaults, revision: 1 }))
    click('Сохранить настройки тренера'); await screen.findByText(/Настройки тренера сохранены/)
    expect(JSON.parse(fetchMock.mock.calls[1][1].body).settings).toMatchObject({
      style: 'showman', address: 'vy', humorKinds: ['self', 'absurd'], edgyOptIn: true, extras: ['trivia'], nickname: 'Лёша' })
  })
  it('hides humor details when humor is off', async () => {
    render(<CoachSettingsPanel />); await loaded()
    expect(screen.getByLabelText('Чёрный юмор (18+)')).not.toBeChecked()
    change('Юмор', 'off')
    expect(screen.queryByLabelText('Чёрный юмор (18+)')).not.toBeInTheDocument()
    expect(screen.queryByRole('group', { name: 'Виды юмора' })).not.toBeInTheDocument()
  })
  it.each([false, true])('missing server operator/vault setup has no plaintext fallback: %s', async operatorSetup => {
    render(<CoachSettingsPanel />); await loaded()
    if (!operatorSetup) await openOperator(false, false)
    else {
      fetchMock.mockResolvedValueOnce(reply({ authorized: true, setupAvailable: true })).mockResolvedValueOnce(reply({ ...credential, storageAvailable: false }))
      click('Доступ оператора Coach'); await screen.findByText(/Настройте защищённое хранилище vault/)
    }
    expect(screen.queryByLabelText('Ключ провайдера')).not.toBeInTheDocument()
    expect(screen.queryByLabelText('Пароль оператора')).not.toBeInTheDocument()
  })
  it('unmount aborts pending requests without rendering late status', async () => {
    const pending = deferred<ReturnType<typeof reply>>()
    fetchMock.mockReturnValueOnce(pending.promise)
    const view = render(<CoachSettingsPanel />)
    const signal = fetchMock.mock.calls[0][1].signal as AbortSignal
    view.unmount(); await act(async () => pending.resolve(reply(defaults)))
    expect(signal.aborted).toBe(true)
    expect(runtime.setSavedCoachPreferences).not.toHaveBeenCalled()
    expect(screen.queryByRole('region', { name: 'AI-тренер' })).not.toBeInTheDocument()
  })
})