import type { ParameterDef } from './types'

// ---------------------------------------------------------------------------
// Lichuan A6 parameter catalog
// Source: Lichuan A6 AC Servo Driver User Manual
// ---------------------------------------------------------------------------

export const PARAMETER_CATALOG: ParameterDef[] = [
  // === Communication ===
  {
    name: 'PA_000', address: 0x000, addressHex: '0x000',
    label: 'Адрес ведомого устройства (Slave ID)',
    group: 'communication', mode: 'ALL',
    min: 0, max: 32, defaultValue: 1, unit: '',
    description: 'Адрес устройства для CANopen и RS485 (0–32). Изменение вступит в силу после перезапуска.',
    requiresReboot: true, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_00D', address: 0x00D, addressHex: '0x00D',
    label: 'Скорость RS485',
    group: 'communication', mode: 'ALL',
    min: 0, max: 6, defaultValue: 3, unit: '',
    description: 'Скорость связи RS485. Формат: 8 data bits, 1 stop bit, even parity.',
    requiresReboot: true, dangerous: false, readOnly: false,
    enumMap: { 0: '2400 bps', 1: '4800 bps', 2: '9600 bps', 3: '19200 bps', 4: '38400 bps', 5: '57600 bps', 6: '115200 bps' },
  },

  // === Control Mode ===
  {
    name: 'PA_002', address: 0x002, addressHex: '0x002',
    label: 'Режим управления',
    group: 'control_mode', mode: 'ALL',
    min: 0, max: 10, defaultValue: 0, unit: '',
    description: 'Выбор режима управления: 0=Position, 1=Speed, 2=Torque, 3=Position/Speed, 4=Position/Torque, 5=Speed/Torque, 10=CANopen.',
    requiresReboot: true, dangerous: false, readOnly: false,
    enumMap: { 0: 'Position', 1: 'Speed', 2: 'Torque', 3: 'Position/Speed', 4: 'Position/Torque', 5: 'Speed/Torque', 10: 'CANopen' },
  },
  {
    name: 'PA_090', address: 0x090, addressHex: '0x090',
    label: 'Расширенный режим управления',
    group: 'control_mode', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Управление через RS485: 0=стандартное (DI/DO), 1=расширенное (Modbus/коммуникация).',
    requiresReboot: false, dangerous: false, readOnly: false,
    enumMap: { 0: 'Стандартный (DI/DO)', 1: 'Расширенный (Modbus)' },
  },
  {
    name: 'PA_091', address: 0x091, addressHex: '0x091',
    label: 'Активный сегмент позиции',
    group: 'position', mode: 'P',
    min: 0, max: 15, defaultValue: 0, unit: '',
    description: 'Индекс активного внутреннего сегмента позиции (0–15).',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_092', address: 0x092, addressHex: '0x092',
    label: 'Активный сегмент скорости',
    group: 'speed', mode: 'S',
    min: 0, max: 31, defaultValue: 0, unit: '',
    description: 'Индекс активного внутреннего сегмента скорости (0–31).',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_093', address: 0x093, addressHex: '0x093',
    label: 'Активный сегмент момента',
    group: 'torque', mode: 'T',
    min: 0, max: 15, defaultValue: 0, unit: '',
    description: 'Индекс активного внутреннего сегмента момента (0–15).',
    requiresReboot: false, dangerous: false, readOnly: false,
  },

  // === Torque limits ===
  {
    name: 'PA_05E', address: 0x05E, addressHex: '0x05E',
    label: 'Ограничение момента (первый лимит)',
    group: 'limits', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 2500, unit: '%',
    description: 'Первый лимит момента. Единица: процент от номинального.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_05F', address: 0x05F, addressHex: '0x05F',
    label: 'Ограничение момента (второй лимит)',
    group: 'limits', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 2500, unit: '%',
    description: 'Второй лимит момента. Единица: процент от номинального.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },

  // === Service command ===
  {
    name: 'PA_1A7', address: 0x1A7, addressHex: '0x1A7',
    label: 'Сервисная команда',
    group: 'save_service', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: '0x0801 — сохранить параметры в EEPROM; 0x0802 — очистить историю ошибок.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },

  // === Monitoring (read-only) ===
  {
    name: 'UN_200', address: 0x200, addressHex: '0x200',
    label: 'Код текущей ошибки',
    group: 'errors', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Текущий активный код аварии. 0 = нет ошибки.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_201', address: 0x201, addressHex: '0x201',
    label: 'Статус DI (битовое поле)',
    group: 'di_do', mode: 'ALL',
    min: 0, max: 0xFF, defaultValue: 0, unit: '',
    description: 'Текущее состояние входов DI0–DI7. Bit0=SRV-ON, Bit1=A-CLR, Bit4=EMG, Bit5=POS_LOAD.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_202', address: 0x202, addressHex: '0x202',
    label: 'Статус DO (битовое поле)',
    group: 'di_do', mode: 'ALL',
    min: 0, max: 0x3F, defaultValue: 0, unit: '',
    description: 'Текущее состояние выходов DO0–DO5.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_203', address: 0x203, addressHex: '0x203',
    label: 'Фактическая скорость',
    group: 'monitoring', mode: 'ALL',
    min: -9999, max: 9999, defaultValue: 0, unit: 'об/мин',
    description: 'Текущая скорость вращения.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_204', address: 0x204, addressHex: '0x204',
    label: 'Фактический момент',
    group: 'monitoring', mode: 'ALL',
    min: -3000, max: 3000, defaultValue: 0, unit: '0.1%',
    description: 'Текущий момент (0.1% от номинального).',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_205', address: 0x205, addressHex: '0x205',
    label: 'Позиция (младшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Младшее слово текущей позиции по обратной связи (32-битное значение).',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_206', address: 0x206, addressHex: '0x206',
    label: 'Позиция (старшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Старшее слово текущей позиции по обратной связи (32-битное значение).',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_207', address: 0x207, addressHex: '0x207',
    label: 'Командная позиция (младшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Младшее слово командной позиции.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_208', address: 0x208, addressHex: '0x208',
    label: 'Командная позиция (старшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Старшее слово командной позиции.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_209', address: 0x209, addressHex: '0x209',
    label: 'Заданная скорость',
    group: 'monitoring', mode: 'S',
    min: -9999, max: 9999, defaultValue: 0, unit: 'об/мин',
    description: 'Заданное значение скорости.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_20A', address: 0x20A, addressHex: '0x20A',
    label: 'Заданный момент',
    group: 'monitoring', mode: 'T',
    min: -3000, max: 3000, defaultValue: 0, unit: '0.1%',
    description: 'Заданное значение момента.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_20B', address: 0x20B, addressHex: '0x20B',
    label: 'Ошибка позиции (младшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Младшее слово ошибки позиции.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'UN_20C', address: 0x20C, addressHex: '0x20C',
    label: 'Ошибка позиции (старшее слово)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: 'Старшее слово ошибки позиции.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
]

const PA_001_ENUM = {
  0: 'Position deviation pulses',
  1: 'Motor speed',
  2: 'Torque output load rate',
  3: 'Control mode',
  4: 'IO status',
  5: 'Alarm / alarm history',
  6: 'Software version',
  7: 'System status',
  8: 'Braking resistor load',
  9: 'Overload rate',
  10: 'Inertia ratio',
  11: 'Feedback pulses total',
  12: 'Command pulses total',
  13: 'External feedback deviation pulses',
  14: 'External feedback pulses',
  15: 'Motor auto-identification',
  16: 'Analog command input',
  17: 'Reason why motor does not turn',
} satisfies Record<number, string>

const CANOPEN_SPEED_ENUM = {
  0: '20 Kbps',
  1: '50 Kbps',
  2: '125 Kbps',
  3: '250 Kbps',
  4: '500 Kbps',
  5: '750 Kbps',
  6: '1 Mbps',
} satisfies Record<number, string>

const DI_FUNCTION_ENUM = {
  0: 'SRV-ON — Servo enable',
  1: 'A-CLR — Alarm clear',
  2: 'CWL — Clockwise stroke limit',
  3: 'CCWL — Counterclockwise stroke limit',
  4: 'C-MODE — Control mode switching',
  5: 'ZEROSPD — Zero speed clamp',
  6: 'DIV — Command pulse frequency selection',
  7: 'SPD_DIR — Speed command direction',
  8: 'INH — Command pulse prohibition',
  9: 'GAIN — Gain switching',
  10: 'CL — Deviation counter clear',
  11: 'INTSPD1 — Internal selection bit 1',
  12: 'INTSPD2 — Internal selection bit 2',
  13: 'INTSPD4 — Internal selection bit 4',
  14: 'INTSPD3 — Internal selection bit 3',
  15: 'TL-SEL — Torque limit switching',
  16: 'Homing — Start homing',
  17: 'ORG_SW — Origin switch',
  18: 'POS_LOCK — Servo locking',
  19: 'JOG_BIT — JOG start',
  20: 'POS_LOAD — Position load',
  21: 'EMG — Emergency stop / external error input',
  22: 'Reserved / not described',
} satisfies Record<number, string>

const DO_FUNCTION_ENUM = {
  0: 'S-RDY — Servo ready',
  1: 'ALM — Servo alarm',
  2: 'COIN — Position arrival',
  3: 'BRK-OFF — Brake release',
  4: 'ZSP — Zero speed detection',
  5: 'TLC — Torque limiting',
  6: 'V-COIN — Speed consistency',
  7: 'AT-SPEED — Speed arrival',
  8: 'EX-COIN — Full closed-loop position arrival',
  9: 'OVERLOAD_O — Overload warning',
  10: 'BRAKE_ON — Brake pipe conduction state',
  11: 'ORG_FOUND — Origin found',
  12: 'Reserved / not supported',
  13: 'Reserved / not supported',
  14: 'BRAKE_ON_ERR_O — Brake error',
  15: 'EEPROM_STATE_O — EEPROM completion status',
  16: 'JOG_RUN — JOG running',
  17: 'Homing_actived — Homing active',
} satisfies Record<number, string>

const HOMING_MODE_ENUM = {
  0: 'Negative origin switch + Z-phase',
  1: 'Positive origin switch + Z-phase',
  2: 'Negative travel limit switch + Z-phase',
  3: 'Positive travel limit switch + Z-phase',
  4: 'Negative origin switch, without Z-phase',
  5: 'Positive origin switch, without Z-phase',
  6: 'Z-phase search in negative direction',
  7: 'Z-phase search in positive direction',
  8: 'Home switch + Z-phase + positive limit, Z left of left edge',
  9: 'Home switch + Z-phase + positive limit, Z right of left edge',
  10: 'Home switch + Z-phase + positive limit, Z left of right edge',
  11: 'Home switch + Z-phase + positive limit, Z right of right edge',
  12: 'Home switch + Z-phase + negative limit, Z right of right edge',
  13: 'Home switch + Z-phase + negative limit, Z left of right edge',
  14: 'Home switch + Z-phase + negative limit, Z right of left edge',
  15: 'Home switch + Z-phase + negative limit, Z left of left edge',
} satisfies Record<number, string>

function formatAddressHex(address: number) {
  return `0x${address.toString(16).toUpperCase().padStart(3, '0')}`
}

function addCatalogEntry(entry: Omit<ParameterDef, 'addressHex'> & { address: number }) {
  PARAMETER_CATALOG.push({
    ...entry,
    addressHex: formatAddressHex(entry.address),
  })
}

function addCatalogEntries(entries: Array<Omit<ParameterDef, 'addressHex'> & { address: number }>) {
  for (const entry of entries) {
    addCatalogEntry(entry)
  }
}

addCatalogEntries([
  {
    name: 'PA_001', address: 0x001,
    label: 'Отображение LED при включении',
    group: 'basic', mode: 'ALL',
    min: 0, max: 17, defaultValue: 0, unit: '',
    description: 'Выбор содержимого LED-индикатора после включения питания.',
    requiresReboot: false, dangerous: false, readOnly: false,
    enumMap: PA_001_ENUM,
  },
  {
    name: 'PA_003', address: 0x003,
    label: 'Источник лимита момента CW/CCW',
    group: 'torque', mode: 'T',
    min: 1, max: 3, defaultValue: 1, unit: '',
    description: 'Выбор источника ограничения момента CW/CCW. Значение 0 в документации помечено как неподдерживаемое.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_004', address: 0x004,
    label: 'Использование входов ограничения хода',
    group: 'basic', mode: 'ALL',
    min: 0, max: 2, defaultValue: 1, unit: '',
    description: 'Настройка использования входов ограничителей хода.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_005', address: 0x005,
    label: 'Источник команды скорости',
    group: 'speed', mode: 'S',
    min: 0, max: 3, defaultValue: 0, unit: '',
    description: 'Источник команды скорости: аналоговый вход или внутренние команды скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_006', address: 0x006,
    label: 'Режим zero-speed clamp / направление скорости',
    group: 'speed', mode: 'S',
    min: 0, max: 2, defaultValue: 0, unit: '',
    description: 'Режим zero-speed clamp или логика задания направления скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_007', address: 0x007,
    label: 'Цифровой фильтр входных импульсов',
    group: 'position', mode: 'P',
    min: 1, max: 15, defaultValue: 2, unit: '',
    description: 'Цифровой фильтр для входа командных импульсов.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_008', address: 0x008,
    label: 'Цифровой фильтр сигнала энкодера',
    group: 'basic', mode: 'ALL',
    min: 1, max: 15, defaultValue: 2, unit: '',
    description: 'Цифровой фильтр сигнала энкодера.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_00A', address: 0x00A,
    label: 'Глубина первого notch-фильтра',
    group: 'gains', mode: 'ALL',
    min: 0, max: 99, defaultValue: 0, unit: '',
    description: 'Глубина первого notch-фильтра. 0 = максимальное подавление, 99 = минимальное.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_00B', address: 0x00B,
    label: 'Использование абсолютного энкодера',
    group: 'basic', mode: 'ALL',
    min: 0, max: 2, defaultValue: 1, unit: '',
    description: 'Настройка режима использования абсолютного энкодера.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_00C', address: 0x00C,
    label: 'Скорость CANopen',
    group: 'communication', mode: 'ALL',
    min: 0, max: 6, defaultValue: 4, unit: '',
    description: 'Скорость обмена CANopen.',
    requiresReboot: true, dangerous: false, readOnly: false,
    enumMap: CANOPEN_SPEED_ENUM,
  },
  {
    name: 'PA_00E', address: 0x00E,
    label: 'Блокировка панели',
    group: 'basic', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Настройка блокировки панели управления.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_00F', address: 0x00F,
    label: 'Коэффициент Pdff / параметр производителя',
    group: 'manufacturer', mode: 'ALL',
    min: 0, max: 100, defaultValue: 65, unit: '',
    description: 'Параметр производителя / коэффициент Pdff feedforward.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_010', address: 0x010,
    label: 'Position loop gain 1',
    group: 'gains', mode: 'P',
    min: 0, max: 1000, defaultValue: 20, unit: '',
    description: 'Первое усиление позиционного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_011', address: 0x011,
    label: 'Speed loop gain 1',
    group: 'gains', mode: 'ALL',
    min: 1, max: 3500, defaultValue: 30, unit: '',
    description: 'Первое усиление скоростного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_012', address: 0x012,
    label: 'Integral time constant 1',
    group: 'gains', mode: 'ALL',
    min: 1, max: 1000, defaultValue: 50, unit: '10 us',
    description: 'Первая интегральная постоянная времени скоростного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_013', address: 0x013,
    label: 'Speed detection filter 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 5, defaultValue: 1, unit: '',
    description: 'Первый фильтр измерения скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_014', address: 0x014,
    label: 'Torque filter time constant 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 25000, defaultValue: 3, unit: '10 us',
    description: 'Первая постоянная времени фильтра момента.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_015', address: 0x015,
    label: 'Rate feed-forward',
    group: 'gains', mode: 'P',
    min: -2000, max: 2000, defaultValue: 500, unit: '0.1%',
    description: 'Коэффициент rate feed-forward.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_016', address: 0x016,
    label: 'Speed feed-forward filter',
    group: 'gains', mode: 'P',
    min: 0, max: 6400, defaultValue: 50, unit: '10 us',
    description: 'Фильтр speed feed-forward.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_017', address: 0x017,
    label: 'Acceleration feed-forward',
    group: 'gains', mode: 'P',
    min: 0, max: 100, defaultValue: 0, unit: '',
    description: 'Коэффициент acceleration feed-forward.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_018', address: 0x018,
    label: 'Position loop gain 2',
    group: 'gains', mode: 'P',
    min: 0, max: 3000, defaultValue: 30, unit: '',
    description: 'Второе усиление позиционного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_019', address: 0x019,
    label: 'Speed loop gain 2',
    group: 'gains', mode: 'ALL',
    min: 1, max: 3500, defaultValue: 40, unit: '',
    description: 'Второе усиление скоростного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01A', address: 0x01A,
    label: 'Integral time constant 2',
    group: 'gains', mode: 'ALL',
    min: 1, max: 1000, defaultValue: 35, unit: '10 us',
    description: 'Вторая интегральная постоянная времени скоростного контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01B', address: 0x01B,
    label: 'Speed detection filter 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 5, defaultValue: 0, unit: '',
    description: 'Второй фильтр измерения скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01C', address: 0x01C,
    label: 'Torque filter time constant 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 25000, defaultValue: 3, unit: '10 us',
    description: 'Вторая постоянная времени фильтра момента.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01D', address: 0x01D,
    label: 'Notch filter frequency 1',
    group: 'gains', mode: 'ALL',
    min: 25, max: 1500, defaultValue: 1500, unit: '',
    description: 'Частота первого notch-фильтра. 1500 отключает фильтр.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01E', address: 0x01E,
    label: 'Notch filter width 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 8, defaultValue: 100, unit: '',
    description: 'Ширина первого notch-фильтра. В мануале есть противоречие: диапазон 0..8, default 100.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_01F', address: 0x01F,
    label: 'Автосброс переполнения позиции',
    group: 'position', mode: 'P',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Автоматический сброс переполнения счётчика позиции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_020', address: 0x020,
    label: 'Отношение инерции нагрузки',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 10000, defaultValue: 100, unit: '%',
    description: 'Отношение инерции нагрузки к инерции ротора.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_021', address: 0x021,
    label: 'Разрешение выбора жёсткости',
    group: 'gains', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Разрешение выбора механической жёсткости / gain level.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_022', address: 0x022,
    label: 'Уровень жёсткости / gain level',
    group: 'gains', mode: 'ALL',
    min: 0, max: 31, defaultValue: 3, unit: '',
    description: 'Уровень механической жёсткости / gain level.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_026', address: 0x026,
    label: 'Алгоритм PID',
    group: 'gains', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Выбор алгоритма PID: Smart PID или I-P.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_028', address: 0x028,
    label: 'Notch filter frequency 2',
    group: 'gains', mode: 'ALL',
    min: 25, max: 1500, defaultValue: 0, unit: '',
    description: 'Частота второго notch-фильтра.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_029', address: 0x029,
    label: 'Notch filter width 2',
    group: 'gains', mode: 'ALL',
    min: 100, max: 1500, defaultValue: 0, unit: '',
    description: 'Ширина второго notch-фильтра.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_02A', address: 0x02A,
    label: 'Notch filter depth 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 99, defaultValue: 0, unit: '',
    description: 'Глубина второго notch-фильтра.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_030', address: 0x030,
    label: 'Переключение gain 1/gain 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 1, defaultValue: 1, unit: '',
    description: 'Разрешить переключение между первым и вторым набором усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_031', address: 0x031,
    label: 'Условие переключения gain 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 2, defaultValue: 0, unit: '',
    description: 'Первое условие переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_032', address: 0x032,
    label: 'Задержка переключения gain 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 10000, defaultValue: 100, unit: '250 us',
    description: 'Первая задержка переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_033', address: 0x033,
    label: 'Уровень переключения gain 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 20000, defaultValue: 50, unit: '',
    description: 'Первый уровень переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_034', address: 0x034,
    label: 'Гистерезис gain 1',
    group: 'gains', mode: 'ALL',
    min: 0, max: 20000, defaultValue: 50, unit: '',
    description: 'Первый гистерезис переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_035', address: 0x035,
    label: 'Время переключения position gain',
    group: 'gains', mode: 'P',
    min: 0, max: 10000, defaultValue: 50, unit: '',
    description: 'Время переключения позиционного усиления.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_036', address: 0x036,
    label: 'Условие переключения gain 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 5, defaultValue: 0, unit: '',
    description: 'Второе условие переключения усилений для speed/torque.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_037', address: 0x037,
    label: 'Задержка переключения gain 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 10000, defaultValue: 100, unit: '',
    description: 'Вторая задержка переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_038', address: 0x038,
    label: 'Уровень переключения gain 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 20000, defaultValue: 100, unit: '',
    description: 'Второй уровень переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_039', address: 0x039,
    label: 'Гистерезис gain 2',
    group: 'gains', mode: 'ALL',
    min: 0, max: 20000, defaultValue: 100, unit: '',
    description: 'Второй гистерезис переключения усилений.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_03A', address: 0x03A,
    label: 'Параметр производителя 03A',
    group: 'manufacturer', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '',
    description: 'Служебный параметр производителя.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_03B', address: 0x03B,
    label: 'Параметр производителя 03B',
    group: 'manufacturer', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '',
    description: 'Служебный параметр производителя.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_03C', address: 0x03C,
    label: 'Параметр производителя 03C',
    group: 'manufacturer', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '',
    description: 'Служебный параметр производителя.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_03D', address: 0x03D,
    label: 'JOG speed',
    group: 'jog', mode: 'ALL',
    min: 0, max: 500, defaultValue: 50, unit: 'об/мин',
    description: 'Скорость JOG.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_03E', address: 0x03E,
    label: 'Версия ПО',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '',
    description: 'Версия программного обеспечения. Только чтение.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_03F', address: 0x03F,
    label: 'Параметр производителя 03F',
    group: 'manufacturer', mode: 'ALL',
    min: -32768, max: 32767, defaultValue: -273, unit: '',
    description: 'Служебный параметр производителя.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_041', address: 0x041,
    label: 'Направление входных импульсов',
    group: 'position', mode: 'P',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Направление вращения для входных командных импульсов.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_042', address: 0x042,
    label: 'Метод входных импульсов',
    group: 'position', mode: 'P',
    min: 0, max: 3, defaultValue: 3, unit: '',
    description: 'Метод входных импульсов: A/B, CW/CCW, pulse+direction и варианты.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_043', address: 0x043,
    label: 'Маскирование INH',
    group: 'position', mode: 'P',
    min: 0, max: 1, defaultValue: 1, unit: '',
    description: 'Команда запрета импульсов INH: активна или маскирована.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_045', address: 0x045,
    label: 'Делитель импульсов обратной связи',
    group: 'position', mode: 'P',
    min: 0, max: 32767, defaultValue: 1, unit: '',
    description: 'Делитель выходных импульсов обратной связи.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_046', address: 0x046,
    label: 'Инверсия / выбор источника feedback pulse',
    group: 'position', mode: 'P',
    min: 0, max: 15, defaultValue: 0, unit: '',
    description: 'Инверсия логики и биты выбора источника импульсов обратной связи.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_048', address: 0x048,
    label: 'Electronic gear numerator 1',
    group: 'position', mode: 'P',
    min: 0, max: 10000, defaultValue: 1, unit: '',
    description: 'Числитель электронного редуктора 1.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_049', address: 0x049,
    label: 'Electronic gear numerator 2',
    group: 'position', mode: 'P',
    min: 0, max: 10000, defaultValue: 1, unit: '',
    description: 'Числитель электронного редуктора 2.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04A', address: 0x04A,
    label: 'Pulses per revolution',
    group: 'position', mode: 'P',
    min: 0, max: 32767, defaultValue: 0, unit: '',
    description: 'Импульсов на оборот. Если 0, используются PA_048 / PA_049 / PA_04B.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04B', address: 0x04B,
    label: 'Electronic gear denominator',
    group: 'position', mode: 'P',
    min: 1, max: 10000, defaultValue: 1, unit: '',
    description: 'Знаменатель электронного редуктора.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04C', address: 0x04C,
    label: 'Command pulse smoothing filter',
    group: 'position', mode: 'P',
    min: 0, max: 7, defaultValue: 1, unit: '',
    description: 'Фильтр сглаживания командных импульсов.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04D', address: 0x04D,
    label: 'FIR filter',
    group: 'position', mode: 'P',
    min: 0, max: 513, defaultValue: 512, unit: '',
    description: 'Параметр FIR-фильтра.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04E', address: 0x04E,
    label: 'Режим очистки deviation counter',
    group: 'position', mode: 'P',
    min: 0, max: 2, defaultValue: 1, unit: '',
    description: 'Режим очистки счётчика отклонения: уровень, фронт или отключено.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_04F', address: 0x04F,
    label: 'Dead zone analog input',
    group: 'speed', mode: 'S',
    min: 0, max: 1000, defaultValue: 10, unit: 'mV',
    description: 'Мёртвая зона аналогового входа.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_050', address: 0x050,
    label: 'Speed command gain',
    group: 'speed', mode: 'S',
    min: 10, max: 2000, defaultValue: 100, unit: 'rpm / V',
    description: 'Коэффициент задания скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_051', address: 0x051,
    label: 'Инверсия analog speed command',
    group: 'speed', mode: 'S',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Инверсия аналоговой команды скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_052', address: 0x052,
    label: 'Zero drift correction',
    group: 'speed', mode: 'ALL',
    min: -2047, max: 2047, defaultValue: 0, unit: 'mV',
    description: 'Коррекция нулевого дрейфа аналоговой команды скорости/момента.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_053', address: 0x053,
    label: 'Internal speed 1',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 1.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_054', address: 0x054,
    label: 'Internal speed 2',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 2.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_055', address: 0x055,
    label: 'Internal speed 3',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 3.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_056', address: 0x056,
    label: 'Internal speed 4 / torque-mode speed limit',
    group: 'speed', mode: 'ALL',
    min: -3000, max: 3000, defaultValue: 500, unit: 'об/мин',
    description: 'Внутренняя скорость 4 или лимит скорости в torque mode.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_057', address: 0x057,
    label: 'Analog command filter',
    group: 'speed', mode: 'ALL',
    min: 0, max: 6400, defaultValue: 100, unit: '10 us',
    description: 'Фильтр внешней аналоговой команды.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_058', address: 0x058,
    label: 'Acceleration time in speed mode',
    group: 'speed', mode: 'S',
    min: 0, max: 2500, defaultValue: 100, unit: 'ms',
    description: 'Время разгона в speed mode для перехода 0 → 1000 rpm.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_059', address: 0x059,
    label: 'Deceleration time in speed mode',
    group: 'speed', mode: 'S',
    min: 0, max: 2500, defaultValue: 100, unit: 'ms',
    description: 'Время торможения в speed mode для перехода 1000 rpm → 0.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_05B', address: 0x05B,
    label: 'Источник torque command',
    group: 'torque', mode: 'T',
    min: 0, max: 0, defaultValue: 0, unit: '',
    description: 'Источник команды момента: внешний аналоговый AI; лимит скорости берётся из PA_056.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_05C', address: 0x05C,
    label: 'Torque command gain',
    group: 'torque', mode: 'T',
    min: 10, max: 100, defaultValue: 50, unit: '',
    description: 'Коэффициент команды момента. Определяет, какое напряжение соответствует 100% номинального момента.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_05D', address: 0x05D,
    label: 'Инверсия analog torque command',
    group: 'torque', mode: 'T',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Инверсия аналоговой команды момента.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_060', address: 0x060,
    label: 'COIN complete range',
    group: 'position', mode: 'P',
    min: 0, max: 20000, defaultValue: 100, unit: 'pulses',
    description: 'Диапазон завершения позиционирования COIN.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_061', address: 0x061,
    label: 'Zero-speed detection threshold',
    group: 'speed', mode: 'ALL',
    min: 10, max: 20000, defaultValue: 10, unit: 'об/мин',
    description: 'Порог детектирования нулевой скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_062', address: 0x062,
    label: 'Speed arrival threshold',
    group: 'speed', mode: 'ALL',
    min: 10, max: 20000, defaultValue: 100, unit: 'об/мин',
    description: 'Порог достижения скорости.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_063', address: 0x063,
    label: 'Condition for COIN output',
    group: 'position', mode: 'P',
    min: 0, max: 3, defaultValue: 0, unit: '',
    description: 'Условие формирования выхода COIN.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_064', address: 0x064,
    label: 'INP/COIN hold time',
    group: 'position', mode: 'P',
    min: 0, max: 30000, defaultValue: 1, unit: 'ms',
    description: 'Время удержания INP/COIN при PA_063 = 3.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_066', address: 0x066,
    label: 'Действие при срабатывании ограничения хода',
    group: 'limits', mode: 'ALL',
    min: 0, max: 2, defaultValue: 2, unit: '',
    description: 'Выбор действия при срабатывании ограничителя хода.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_06A', address: 0x06A,
    label: 'Задержка механического тормоза (стоп)',
    group: 'basic', mode: 'ALL',
    min: 0, max: 100, defaultValue: 50, unit: 'x2 ms',
    description: 'Задержка механического тормоза при остановленном двигателе.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_06B', address: 0x06B,
    label: 'Задержка механического тормоза (run)',
    group: 'basic', mode: 'ALL',
    min: 0, max: 100, defaultValue: 50, unit: 'x2 ms',
    description: 'Задержка механического тормоза при работающем двигателе.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_06C', address: 0x06C,
    label: 'Резистор торможения / Err18',
    group: 'basic', mode: 'ALL',
    min: 0, max: 3, defaultValue: 0, unit: '',
    description: 'Настройка внутреннего/внешнего резистора торможения и защиты Err18.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_06E', address: 0x06E,
    label: 'Speed limit for EMG / stroke limit',
    group: 'limits', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 2500, unit: 'об/мин',
    description: 'Скорость/лимит для аварийной остановки или ограничения хода. Используется с PA_066 = 2.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_070', address: 0x070,
    label: 'Excessive position deviation threshold',
    group: 'limits', mode: 'P',
    min: 0, max: 32767, defaultValue: 0, unit: '',
    description: 'Порог чрезмерного отклонения позиции. 0 отключает проверку.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_071', address: 0x071,
    label: 'Analog command overvoltage threshold',
    group: 'limits', mode: 'ALL',
    min: 0, max: 100, defaultValue: 100, unit: '0.1 V',
    description: 'Порог перенапряжения аналоговой команды. 0 отключает проверку.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_072', address: 0x072,
    label: 'Overload level',
    group: 'limits', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 0, unit: '',
    description: 'Уровень перегрузки.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_073', address: 0x073,
    label: 'Overspeed level',
    group: 'limits', mode: 'ALL',
    min: 0, max: 20000, defaultValue: 0, unit: 'об/мин',
    description: 'Уровень превышения скорости. 0 означает 1.2× максимальной скорости двигателя.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_074', address: 0x074,
    label: 'Internal speed 5',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 5.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_075', address: 0x075,
    label: 'Internal speed 6',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 6.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_076', address: 0x076,
    label: 'Internal speed 7',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 7.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_077', address: 0x077,
    label: 'Internal speed 8',
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: 'Внутренняя скорость 8.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_07D', address: 0x07D,
    label: 'Current loop gain',
    group: 'gains', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '',
    description: 'Усиление токового контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_07E', address: 0x07E,
    label: 'Current loop integral time constant',
    group: 'gains', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: '62.5 us',
    description: 'Интегральная постоянная времени токового контура.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_07F', address: 0x07F,
    label: 'Dead zone',
    group: 'gains', mode: 'ALL',
    min: 1000, max: 5000, defaultValue: 2000, unit: 'us',
    description: 'Параметр dead zone.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_08E', address: 0x08E,
    label: 'IO polarity configuration',
    group: 'di_do', mode: 'ALL',
    min: -32768, max: 32767, defaultValue: 0, unit: '',
    description: 'Полярность IO: младшие 8 бит соответствуют DI0..DI7, старшие 8 бит — DO0..DO5.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_08F', address: 0x08F,
    label: 'Servo enable mode',
    group: 'basic', mode: 'ALL',
    min: 0, max: 2, defaultValue: 0, unit: '',
    description: 'Режим включения сервопривода. 0 = external/communication enable, 1 = automatic enable after power-on.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_094', address: 0x094,
    label: 'Absolute / relative position mode bits',
    group: 'position', mode: 'P',
    min: 0, max: 7, defaultValue: 0, unit: '',
    description: 'Битовая настройка absolute / relative position mode.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_096', address: 0x096,
    label: 'Multi-segment position loading mode',
    group: 'position', mode: 'P',
    min: 0, max: 2, defaultValue: 0, unit: '',
    description: 'Режим загрузки многосегментной позиции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A0', address: 0x0A0,
    label: 'Zeroing method',
    group: 'homing', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Метод возврата в ноль. 0 = homing by signal, 1 = automatic zero return at power-on.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A1', address: 0x0A1,
    label: 'Homing / zero return mode',
    group: 'homing', mode: 'ALL',
    min: 0, max: 15, defaultValue: 12, unit: '',
    description: 'Режим homing / zero return.',
    requiresReboot: false, dangerous: false, readOnly: false,
    enumMap: HOMING_MODE_ENUM,
  },
  {
    name: 'PA_0A2', address: 0x0A2,
    label: 'High speed for homing',
    group: 'homing', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 300, unit: 'об/мин',
    description: 'Высокая скорость поиска нуля.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A3', address: 0x0A3,
    label: 'Low speed for homing',
    group: 'homing', mode: 'ALL',
    min: 0, max: 500, defaultValue: 50, unit: 'об/мин',
    description: 'Низкая скорость поиска нуля.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A4', address: 0x0A4,
    label: 'Acceleration / deceleration for homing',
    group: 'homing', mode: 'ALL',
    min: 0, max: 2500, defaultValue: 100, unit: '',
    description: 'Время ускорения / замедления во время поиска нуля.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A5', address: 0x0A5,
    label: 'Mechanical origin offset',
    group: 'homing', mode: 'ALL',
    min: -32768, max: 32767, defaultValue: 0, unit: '',
    description: 'Механическое смещение нуля.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A6', address: 0x0A6,
    label: 'Origin search timeout',
    group: 'homing', mode: 'ALL',
    min: 0, max: 1000, defaultValue: 0, unit: '100 ms',
    description: 'Таймаут поиска нуля. 0 означает отсутствие ошибки по времени.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A8', address: 0x0A8,
    label: 'Inertia recognition mode',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 0, defaultValue: 0, unit: '',
    description: 'Режим распознавания инерции: offline tuning.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0A9', address: 0x0A9,
    label: 'Max speed for inertia recognition',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 3000, defaultValue: 800, unit: 'об/мин',
    description: 'Максимальная скорость при распознавании инерции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0AA', address: 0x0AA,
    label: 'Acceleration time for inertia recognition',
    group: 'inertia', mode: 'ALL',
    min: 5, max: 1000, defaultValue: 100, unit: 'ms',
    description: 'Время разгона при распознавании инерции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0AB', address: 0x0AB,
    label: 'First rotation direction for inertia recognition',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Первое направление вращения при распознавании инерции. 0 = CCW, 1 = CW.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0AC', address: 0x0AC,
    label: 'Max angular displacement for inertia recognition',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 10, unit: '0.1 rev',
    description: 'Максимальное угловое смещение при распознавании инерции. Только чтение.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_0AD', address: 0x0AD,
    label: 'Number of inertia tuning cycles',
    group: 'inertia', mode: 'ALL',
    min: 1, max: 10, defaultValue: 2, unit: '',
    description: 'Количество циклов теста распознавания инерции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0AE', address: 0x0AE,
    label: 'Measured inertia value',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: 'x10^-6 kg*m^2',
    description: 'Измеренное значение инерции. Только чтение.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_0AF', address: 0x0AF,
    label: 'Inertia setting enable',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 2, defaultValue: 0, unit: '',
    description: 'Разрешение применения результатов настройки инерции.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_0B2', address: 0x0B2,
    label: 'Inertia tuning result',
    group: 'inertia', mode: 'ALL',
    min: 0, max: 1, defaultValue: 0, unit: '',
    description: 'Результат настройки инерции. 1 = completed, 0 = error.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1A0', address: 0x1A0,
    label: 'Источник DI: внешний или communication IO',
    group: 'communication_control', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: 'bit mask',
    description: 'Выбор между внешними DI и simulated / communication IO для DI0..DI7.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
  {
    name: 'PA_1A4', address: 0x1A4,
    label: 'Communication simulation IO',
    group: 'communication_control', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: 'bit mask',
    description: 'Симулируемые communication IO. Биты эквивалентны DI0..DI7.',
    requiresReboot: false, dangerous: true, readOnly: false,
  },
  {
    name: 'PA_1A5', address: 0x1A5,
    label: 'Communication analog IO mask',
    group: 'communication_control', mode: 'ALL',
    min: 0, max: 65535, defaultValue: 0, unit: 'bit mask',
    description: 'Маска communication analog IO.',
    requiresReboot: false, dangerous: false, readOnly: false,
  },
])

for (let i = 0; i < 8; i++) {
  addCatalogEntry({
    name: `PA_${(0x080 + i).toString(16).toUpperCase().padStart(3, '0')}`,
    address: 0x080 + i,
    label: `DI${i} function`,
    group: 'di_do', mode: 'ALL',
    min: 0, max: 22, defaultValue: [0, 1, 2, 3, 10, 8, 15, 16][i], unit: '',
    description: `Конфигурация функции цифрового входа DI${i}.`,
    requiresReboot: false, dangerous: false, readOnly: false,
    enumMap: DI_FUNCTION_ENUM,
  })
}

for (let i = 0; i < 6; i++) {
  addCatalogEntry({
    name: `PA_${(0x088 + i).toString(16).toUpperCase().padStart(3, '0')}`,
    address: 0x088 + i,
    label: `DO${i} function`,
    group: 'di_do', mode: 'ALL',
    min: 0, max: 17, defaultValue: i, unit: '',
    description: `Конфигурация функции цифрового выхода DO${i}.`,
    requiresReboot: false, dangerous: false, readOnly: false,
    enumMap: DO_FUNCTION_ENUM,
  })
}

for (let i = 0; i < 10; i++) {
  addCatalogEntry({
    name: `PA_${(0x121 + i).toString(16).toUpperCase().padStart(3, '0')}`,
    address: 0x121 + i,
    label: `История ошибок ${i}`,
    group: 'errors', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: `Код ошибки из истории аварий, слот ${i}. Только чтение.`,
    requiresReboot: false, dangerous: false, readOnly: true,
  })
}

addCatalogEntries([
  {
    name: 'PA_1B6', address: 0x1B6,
    label: 'Position instruction overflow (low)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Переполнение инструкции позиции: младшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1B7', address: 0x1B7,
    label: 'Position instruction overflow (high)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Переполнение инструкции позиции: старшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1B8', address: 0x1B8,
    label: 'Command position (low)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Командная позиция: младшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1B9', address: 0x1B9,
    label: 'Command position (high)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Командная позиция: старшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BA', address: 0x1BA,
    label: 'User coordinate (low)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Пользовательская координата: младшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BB', address: 0x1BB,
    label: 'User coordinate (high)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Пользовательская координата: старшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BC', address: 0x1BC,
    label: 'Position feedback (low)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Обратная связь по позиции: младшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BD', address: 0x1BD,
    label: 'Position feedback (high)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Обратная связь по позиции: старшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BE', address: 0x1BE,
    label: 'Position deviation (low)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Отклонение позиции: младшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1BF', address: 0x1BF,
    label: 'Position deviation (high)',
    group: 'monitoring', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Отклонение позиции: старшие 16 бит.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C0', address: 0x1C0,
    label: 'Current command speed',
    group: 'monitoring', mode: 'S',
    min: -32768, max: 32767, defaultValue: 0, unit: 'об/мин',
    description: 'Текущее заданное значение скорости.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C1', address: 0x1C1,
    label: 'Current feedback speed',
    group: 'monitoring', mode: 'S',
    min: -32768, max: 32767, defaultValue: 0, unit: 'об/мин',
    description: 'Текущая фактическая скорость.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C2', address: 0x1C2,
    label: 'Current speed deviation',
    group: 'monitoring', mode: 'S',
    min: -32768, max: 32767, defaultValue: 0, unit: 'об/мин',
    description: 'Текущее отклонение скорости.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C3', address: 0x1C3,
    label: 'Current command torque',
    group: 'monitoring', mode: 'T',
    min: -32768, max: 32767, defaultValue: 0, unit: '0.1%',
    description: 'Текущее заданное значение момента.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C4', address: 0x1C4,
    label: 'Current feedback torque',
    group: 'monitoring', mode: 'T',
    min: -32768, max: 32767, defaultValue: 0, unit: '0.1%',
    description: 'Текущее фактическое значение момента.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C5', address: 0x1C5,
    label: 'Current torque deviation',
    group: 'monitoring', mode: 'T',
    min: -32768, max: 32767, defaultValue: 0, unit: '0.1%',
    description: 'Текущее отклонение момента.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C8', address: 0x1C8,
    label: 'System status',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Системный статус.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1C9', address: 0x1C9,
    label: 'Error code',
    group: 'errors', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Текущий код ошибки.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CA', address: 0x1CA,
    label: 'Current control mode',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Текущий режим управления.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CB', address: 0x1CB,
    label: 'Current position index',
    group: 'monitoring', mode: 'P',
    min: 0, max: 20, defaultValue: 0, unit: '',
    description: 'Текущий индекс позиции.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CC', address: 0x1CC,
    label: 'Current speed index',
    group: 'monitoring', mode: 'S',
    min: 0, max: 36, defaultValue: 0, unit: '',
    description: 'Текущий индекс скорости.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CD', address: 0x1CD,
    label: 'Current torque index',
    group: 'monitoring', mode: 'T',
    min: 0, max: 36, defaultValue: 0, unit: '',
    description: 'Текущий индекс момента.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CE', address: 0x1CE,
    label: 'Servo command / status bits (low)',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Биты команд / статуса сервопривода: младшее слово.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1CF', address: 0x1CF,
    label: 'Servo command / status bits (high)',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Биты команд / статуса сервопривода: старшее слово.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D0', address: 0x1D0,
    label: 'Servo status bits (low)',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Биты статуса сервопривода: младшее слово.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D1', address: 0x1D1,
    label: 'Servo status bits (high)',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Биты статуса сервопривода: старшее слово.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D2', address: 0x1D2,
    label: 'Digital DI input state',
    group: 'di_do', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Состояние цифровых входов DI. Bit0 = DI0 ... Bit7 = DI7.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D3', address: 0x1D3,
    label: 'Digital DO output state',
    group: 'di_do', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Состояние цифровых выходов DO. Bit0 = DO0 ... Bit5 = DO5.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D4', address: 0x1D4,
    label: 'Analog input AI0',
    group: 'monitoring', mode: 'ALL',
    min: -32768, max: 32767, defaultValue: 0, unit: 'mV',
    description: 'Текущее значение аналогового входа AI0.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1D9', address: 0x1D9,
    label: 'DC bus voltage',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'V',
    description: 'Напряжение DC-шины.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1DA', address: 0x1DA,
    label: 'Module temperature ADC',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'ADC-значение температуры модуля.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1DB', address: 0x1DB,
    label: 'Torque load ratio',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '%',
    description: 'Коэффициент загрузки по моменту.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1DC', address: 0x1DC,
    label: 'Braking resistor load rate',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '%',
    description: 'Коэффициент загрузки тормозного резистора.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1DD', address: 0x1DD,
    label: 'Torque overload rate',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '%',
    description: 'Коэффициент перегрузки по моменту.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
  {
    name: 'PA_1DE', address: 0x1DE,
    label: 'Reason motor does not start',
    group: 'monitoring', mode: 'ALL',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: '',
    description: 'Причина, по которой двигатель не запускается.',
    requiresReboot: false, dangerous: false, readOnly: true,
  },
])

// Generate position segment entries PA_168..PA_187 (low) & PA_169..PA_188 (high)
// and speed entries for position segments PA_190..PA_19F
for (let i = 0; i < 16; i++) {
  const addrLow = 0x168 + i * 2
  const addrHigh = 0x168 + i * 2 + 1
  const addrSpeed = 0x190 + i

  PARAMETER_CATALOG.push({
    name: `PA_${(addrLow).toString(16).toUpperCase().padStart(3, '0')}`,
    address: addrLow,
    addressHex: `0x${addrLow.toString(16).toUpperCase().padStart(3, '0')}`,
    label: `Сегмент позиции ${i} — младшее слово`,
    group: 'position', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: `Младшее слово позиции для сегмента ${i}.`,
    requiresReboot: false, dangerous: false, readOnly: false,
  })
  PARAMETER_CATALOG.push({
    name: `PA_${(addrHigh).toString(16).toUpperCase().padStart(3, '0')}`,
    address: addrHigh,
    addressHex: `0x${addrHigh.toString(16).toUpperCase().padStart(3, '0')}`,
    label: `Сегмент позиции ${i} — старшее слово`,
    group: 'position', mode: 'P',
    min: 0, max: 0xFFFF, defaultValue: 0, unit: 'имп',
    description: `Старшее слово позиции для сегмента ${i}.`,
    requiresReboot: false, dangerous: false, readOnly: false,
  })
  PARAMETER_CATALOG.push({
    name: `PA_${(addrSpeed).toString(16).toUpperCase().padStart(3, '0')}`,
    address: addrSpeed,
    addressHex: `0x${addrSpeed.toString(16).toUpperCase().padStart(3, '0')}`,
    label: `Скорость сегмента позиции ${i}`,
    group: 'position', mode: 'P',
    min: 1, max: 3000, defaultValue: 500, unit: 'об/мин',
    description: `Скорость перемещения для сегмента позиции ${i}.`,
    requiresReboot: false, dangerous: false, readOnly: false,
  })
}

// Speed segments PA_150..PA_16F
for (let i = 0; i < 32; i++) {
  const addr = 0x150 + i
  PARAMETER_CATALOG.push({
    name: `PA_${addr.toString(16).toUpperCase().padStart(3, '0')}`,
    address: addr,
    addressHex: `0x${addr.toString(16).toUpperCase().padStart(3, '0')}`,
    label: `Сегмент скорости ${i}`,
    group: 'speed', mode: 'S',
    min: -3000, max: 3000, defaultValue: 0, unit: 'об/мин',
    description: `Значение скорости для внутреннего сегмента ${i}. Отрицательное = CCW.`,
    requiresReboot: false, dangerous: false, readOnly: false,
  })
}

// Torque segments PA_12C..PA_14B
for (let i = 0; i < 32; i++) {
  const addr = 0x12C + i
  PARAMETER_CATALOG.push({
    name: `PA_${addr.toString(16).toUpperCase().padStart(3, '0')}`,
    address: addr,
    addressHex: `0x${addr.toString(16).toUpperCase().padStart(3, '0')}`,
    label: `Сегмент момента ${i}`,
    group: 'torque', mode: 'T',
    min: -3000, max: 3000, defaultValue: 0, unit: '0.1%',
    description: `Значение момента для сегмента ${i}. 0.1% от номинального. Опасно — требует подтверждения.`,
    requiresReboot: false, dangerous: true, readOnly: false,
  })
}

// Index by address for fast lookup
PARAMETER_CATALOG.sort((left, right) => left.address - right.address)

export const CATALOG_BY_ADDRESS = new Map<number, ParameterDef>(
  PARAMETER_CATALOG.map((p) => [p.address, p]),
)

export const GROUP_LABELS: Record<string, string> = {
  basic: 'Базовые',
  communication: 'Связь',
  control_mode: 'Режим управления',
  communication_control: 'Управление по связи',
  position: 'Position mode',
  speed: 'Speed mode',
  torque: 'Torque mode',
  di_do: 'DI/DO',
  monitoring: 'Мониторинг',
  errors: 'Ошибки',
  save_service: 'Сохранение / Сервис',
  service: 'Сервис',
  jog: 'JOG',
  homing: 'Homing',
  limits: 'Ограничения и защита',
  gains: 'Усиления / Регулятор',
  inertia: 'Инерция / автонастройка',
  manufacturer: 'Параметры производителя',
}

export const BAUD_RATE_LABELS: Record<number, string> = {
  0: '2400 bps',
  1: '4800 bps',
  2: '9600 bps',
  3: '19200 bps',
  4: '38400 bps',
  5: '57600 bps',
  6: '115200 bps',
}

export const CONTROL_MODE_LABELS: Record<number, string> = {
  0: 'Position',
  1: 'Speed',
  2: 'Torque',
  3: 'Position/Speed',
  4: 'Position/Torque',
  5: 'Speed/Torque',
  10: 'CANopen',
}

// DI bit descriptions
export const DI_BIT_LABELS: Record<number, { name: string; description: string }> = {
  0: { name: 'SRV-ON', description: 'Servo ON — включение серводвигателя' },
  1: { name: 'A-CLR', description: 'Сброс аварийного сигнала' },
  2: { name: 'CWL', description: 'Ограничение хода CW (по часовой)' },
  3: { name: 'CCWL', description: 'Ограничение хода CCW (против часовой)' },
  4: { name: 'EMG', description: 'Аварийная остановка (Emergency Stop)' },
  5: { name: 'POS_LOAD', description: 'Загрузка позиции из сегмента' },
  6: { name: 'JOG_BIT', description: 'Запуск JOG (ручное управление)' },
  7: { name: 'ORG_SW', description: 'Датчик нулевого положения' },
}

// DO bit descriptions
export const DO_BIT_LABELS: Record<number, { name: string; description: string }> = {
  0: { name: 'SRDY', description: 'Servo Ready — серво готово' },
  1: { name: 'ALM', description: 'Alarm — активная авария' },
  2: { name: 'INP', description: 'In Position — позиция достигнута' },
  3: { name: 'BRK', description: 'Brake Release — тормоз отпущен' },
  4: { name: 'ZSP', description: 'Zero Speed — нулевая скорость' },
  5: { name: 'TL-SEL', description: 'Torque Limiting — ограничение момента активно' },
}

// Alarm code descriptions
export const ALARM_CODES: Record<number, { label: string; causes: string; action: string; canReset: boolean }> = {
  0: { label: 'Нет ошибки', causes: '', action: '', canReset: false },
  1: { label: 'Превышение тока', causes: 'Короткое замыкание, неисправность UVW, перегрузка', action: 'Проверить проводку UVW и энкодер', canReset: true },
  2: { label: 'Превышение напряжения', causes: 'Слишком высокое напряжение питания', action: 'Проверить напряжение питания', canReset: true },
  3: { label: 'Пониженное напряжение', causes: 'Нестабильное питание', action: 'Проверить питание и предохранители', canReset: true },
  4: { label: 'Перегрев', causes: 'Высокая температура драйвера', action: 'Улучшить вентиляцию', canReset: true },
  6: { label: 'Ошибка кодировщика', causes: 'Неисправность или обрыв энкодера', action: 'Проверить кабель и разъём энкодера', canReset: false },
  7: { label: 'Аварийная остановка активна', causes: 'EMG вход активирован', action: 'Снять сигнал EMG', canReset: true },
  8: { label: 'Перегрузка', causes: 'Продолжительная нагрузка превышает номинал', action: 'Снизить нагрузку', canReset: true },
  9: { label: 'Ошибка скорости', causes: 'Скорость выше допустимой', action: 'Проверить настройки и нагрузку', canReset: true },
  10: { label: 'Ошибка позиции', causes: 'Ошибка отслеживания позиции слишком велика', action: 'Проверить механику и усиления', canReset: true },
  16: { label: 'Ошибка EEPROM', causes: 'Сбой при записи параметров', action: 'Выполнить заводской сброс', canReset: false },
}
