import { expect } from '@playwright/test'
import { openAppAsAlexey, savedBrowserState, test } from './fixtures/navigation'
import { buildDashboardScenario } from '../src/mocks/data'

for (const viewport of [{ width: 3840, height: 2160 }, { width: 1920, height: 1080 }]) {
  for (const count of [3, 4]) {
    test(`${count} home workout cards at ${viewport.width}x${viewport.height}`, async ({ page, navigationApi }, testInfo) => {
      await page.setViewportSize(viewport)
      const dashboard = buildDashboardScenario()
      dashboard.muscles = [{ name: 'Грудь', status: 'critical', score: 150 }, { name: 'Икры', status: 'no_data', score: 0 }]
      dashboard.workouts = Array.from({ length: count }, (_, index) => ({
        id: `personal ${index}`, title: ['Спина и бицепс', 'Грудь и плечи', 'Ноги', 'Общая тренировка'][index], duration: '≈ 45 минут',
        lastPerformedAt: '2026-09-13T12:00:00Z', lastStatus: 'completed',
        exercises: Array.from({ length: 7 }, (_, row) => ({ slug: `exercise-${row}`, name: `Упражнение ${row + 1}` })),
      }))
      await page.route('**/api/dashboard?**', (route) => route.fulfill({ json: dashboard }))
      await openAppAsAlexey(page)
      const state = await savedBrowserState(page)
      await expect(page.getByRole('dialog')).toHaveCount(0)
      const cards = page.getByRole('button', { name: /^Выбрать тренировку «/ })
      await expect(cards).toHaveCount(count)
      await expect(page.getByRole('button', { name: /Новая тренировка/ })).toHaveCount(count < 4 ? 1 : 0)
      for (const card of await cards.all()) await expect(card).toBeInViewport({ ratio: 1 })
      expect(await page.locator('main').evaluate((node) => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(2)
      expect(await page.locator('main').evaluate((node) => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(2)
      await expect(page.getByText(/Карта усталости|Статистика|Сбросить прогресс дня/)).toHaveCount(0)
      const recovery = page.getByRole('region', { name: 'Восстановление мышц', exact: true })
      await expect(recovery).toBeVisible()
      await expect(recovery).toBeInViewport({ ratio: 1 })
      await expect(page.getByRole('button', { name: 'Карта мышц', exact: true })).toHaveCount(0)
      await expect(page.getByRole('list', { name: 'Краткая сводка усталости' })).toHaveCount(0)
      const figures = recovery.locator('.home-recovery-figure')
      await expect(figures).toHaveCount(2)
      const front = recovery.locator('.home-recovery-figure[id$="-front"]')
      const back = recovery.locator('.home-recovery-figure[id$="-back"]')
      for (const figure of [front, back]) {
        await expect(figure).toBeInViewport({ ratio: 1 })
        await expect(figure.locator('svg:not([data-compact-body-outline-overlay])')).toBeVisible()
      }
      const frontBox = await front.boundingBox()
      const backBox = await back.boundingBox()
      expect(frontBox!.y + frontBox!.height).toBeLessThanOrEqual(backBox!.y)
      expect(Math.abs(frontBox!.x + frontBox!.width / 2 - backBox!.x - backBox!.width / 2)).toBeLessThanOrEqual(2)
      const recoveryBox = await recovery.boundingBox()
      for (const card of await cards.all()) {
        const cardBox = await card.boundingBox()
        expect(cardBox!.x + cardBox!.width).toBeLessThanOrEqual(recoveryBox!.x)
      }
      const chest = front.getByRole('button', { name: /^Грудь:/ }).first()
      await expect(chest).toHaveAttribute('aria-label', 'Грудь: Перегрузка, 150 балл.')
      await expect(chest).toHaveAttribute('tabindex', '0')
      const chestPath = chest.locator('path').first()
      await chestPath.hover()
      const tooltip = recovery.getByRole('tooltip')
      await expect(tooltip).toBeVisible()
      await expect(tooltip.getByText('Грудь', { exact: true })).toBeVisible()
      await expect(tooltip.getByText('Перегрузка', { exact: true })).toBeVisible()
      await expect(tooltip.locator('.home-recovery-score')).toHaveText('150 балл. усталости')
      expect(await savedBrowserState(page)).toEqual(state)
      const recoveryShot = testInfo.outputPath('recovery.png')
      await page.screenshot({ path: recoveryShot })
      await testInfo.attach('recovery', { path: recoveryShot, contentType: 'image/png' })
      await recovery.getByRole('heading', { name: 'Усталость мышц' }).hover()
      await expect(tooltip).toHaveCount(0)
      await chest.focus()
      await expect(chest).toBeFocused()
      await expect(tooltip).toBeVisible()
      await expect(tooltip.getByText('Грудь', { exact: true })).toBeVisible()
      await expect(tooltip.locator('.home-recovery-score')).toHaveText('150 балл. усталости')
      await page.keyboard.press('Escape')
      await expect(tooltip).toHaveCount(0)
      await expect(chest).toBeFocused()
      await chestPath.click()
      await expect(tooltip).toBeVisible()
      await chest.press('Escape')
      await expect(tooltip).toHaveCount(0)
      await expect(page.getByRole('dialog')).toHaveCount(0)
      await expect(recovery).toBeVisible()
      expect(await savedBrowserState(page)).toEqual(state)
      expect(await page.locator('main').evaluate((node) => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(2)
      expect(await page.locator('main').evaluate((node) => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(2)
      const shot = testInfo.outputPath('home.png')
      await page.screenshot({ path: shot })
      await testInfo.attach('home', { path: shot, contentType: 'image/png' })

      await cards.first().press('Enter')
      const dialog = page.getByRole('dialog', { name: 'Спина и бицепс' })
      await expect(dialog).toBeVisible()
      await expect(page).toHaveURL(/\/dashboard$/)
      expect(await savedBrowserState(page)).toEqual(state)
      await expect(dialog.getByRole('listitem')).toHaveCount(7)
      for (const name of ['Начать', 'Изменить', 'Назад', 'Аварийная остановка']) await expect(dialog.getByRole('button', { name, exact: true })).toBeInViewport()
      const panel = await page.locator('.home-confirm-panel').boundingBox()
      const dock = await page.locator('.forma-system-dock').boundingBox()
      expect(panel!.y).toBeGreaterThanOrEqual(dock!.y + dock!.height)
      expect(panel!.y + panel!.height).toBeLessThanOrEqual(viewport.height)
      await dialog.getByRole('button', { name: 'Назад', exact: true }).click()
      await expect(dialog).toHaveCount(0)
      await expect(cards.first()).toBeFocused()
      expect(await savedBrowserState(page)).toEqual(state)
      await cards.first().click()
      await page.getByRole('dialog').getByRole('button', { name: 'Изменить', exact: true }).click()
      await expect(page).toHaveURL(/\/builder\?programId=personal%200$/)
      expect(navigationApi.requests.filter(({ path }) => path.startsWith('/api/runtime'))).toEqual([])
      await page.goto('/dashboard')
      await expect(page.getByRole('dialog')).toHaveCount(0)
      if (count < 4) {
        await page.getByRole('button', { name: /Новая тренировка/ }).click()
        await expect(page).toHaveURL(/\/builder\?create=new$/)
        await expect(page.getByRole('dialog')).toBeVisible()
        expect(navigationApi.requests.filter(({ method }) => method !== 'GET' && method !== 'POST')).toEqual([])
      }
    })
  }
}